const locations=[
{id:'anenuma_ice',lat:40.749,lon:141.322,label:'青森｜姉沼｜氷上',water:'姉沼',style:'氷上',months:[1,2],shelf:'浅場中心',rig:'短め 4〜6本針',sinker:'2〜4g',bait:'白サシ・紅サシ',tip:'繊細〜中間',baseCatch:120,exposure:'ice',special:'汽水湖で氷が緩みやすい。年変動が大きく、好調年は短時間で爆発する。',localItems:['カイロ','甘い缶コーヒー']},
{id:'gandoko_ice',lat:39.804,lon:141.149,label:'岩手｜岩洞湖｜氷上',water:'岩洞湖',style:'氷上',months:[1,2,3],shelf:'浅場か深場を魚探で選択',rig:'5〜7本針',sinker:'3〜5g',bait:'白サシ・紅サシ',tip:'先調子〜中間',baseCatch:140,exposure:'ice',special:'同一ポイント2日目は極端に落ちることがある。移動判断を早めに。',localItems:['ソフトクリーム','予備バッテリー']},
{id:'gandoko_dome',lat:39.804,lon:141.149,label:'岩手｜岩洞湖｜ドーム船',water:'岩洞湖',style:'ドーム船',months:[11,12,1,2,3],shelf:'底中心',rig:'5〜7本針',sinker:'4〜5g',bait:'白サシ・紅サシ',tip:'柔らかめ〜中間',baseCatch:45,exposure:'dome',special:'ドームは釣果が伸びにくい日もある。小さな変化を拾う釣りが吉。',localItems:['温かいココア','ソフトクリーム']},
{id:'sai_ice',lat:39.741,lon:141.378,label:'岩手｜菜魚湖・大志田ダム｜氷上',water:'菜魚湖・大志田ダム',style:'氷上',months:[1,2],shelf:'底中心',rig:'標準 5本前後',sinker:'3〜5g',bait:'サシ系',tip:'中間',baseCatch:90,exposure:'ice',special:'年ごとの開催状況に左右される。現地の開場情報を最優先。',localItems:['湯たんぽ','カップ麺']},
{id:'hanayama_dome',lat:38.789,lon:140.857,label:'宮城｜花山湖｜ドーム船',water:'花山湖',style:'ドーム船',months:[11,12,1,2,3],shelf:'底〜中層',rig:'底なら短め5本 / 中層なら長め7本',sinker:'赤 5〜7g',bait:'赤虫・紅サシ',tip:'連掛け向き・やや硬め',baseCatch:180,exposure:'dome',special:'蛍光オモリは嫌われがち。赤オモリが基本。小型が多く手返し重視。',localItems:['天丼','自然薯の館','土井工房の針外し']},
{id:'minamikawa_bridge',lat:38.411,lon:140.905,label:'宮城｜南川ダム｜橋上',water:'南川ダム',style:'橋上',months:[10,11,12,1,2],shelf:'底中心',rig:'長め 4〜8本針',sinker:'7・10・14g中心',bait:'サシ・赤虫',tip:'硬め＋延長30cm',baseCatch:95,exposure:'outdoor',special:'朝、特に8時前が強い。風が出ると重めへ寄せる。',localItems:['コーヒー牛乳','防風手袋','南川会の最新投稿']},
{id:'wakuya_pier',lat:38.543,lon:141.134,label:'宮城｜涌谷町釣り公園｜桟橋',water:'涌谷町釣り公園',style:'桟橋',months:[10,11,12,1,2],shelf:'魚探シューティング',rig:'5本針・1.5号以上',sinker:'3〜5g',bait:'白サシ',tip:'大型対応・硬め',baseCatch:18,exposure:'outdoor',special:'基本は大型狙い。外道のモロコに惑わされず魚探反応を絞る。',localItems:['蓋付き魚入れ','白サシ','猫']},
{id:'towada_dome',lat:40.442,lon:140.887,label:'秋田｜十和田湖・小坂側｜ドーム船',water:'十和田湖・小坂側',style:'ドーム船',months:[11,12,1,2,3],shelf:'深場中心',rig:'標準 5〜7本針',sinker:'4〜6g',bait:'サシ系',tip:'中間',baseCatch:60,exposure:'dome',special:'風による運休に注意。最新営業情報の確認を優先。',localItems:['温泉','甘酒']},
{id:'hibara_s_dome',lat:37.689,lon:140.071,label:'福島｜桧原湖南部｜屋形・ドーム',water:'桧原湖南部',style:'屋形・ドーム',months:[11,12,1,2,3],shelf:'底中心',rig:'狐0.8号前後・短め',sinker:'3〜5g',bait:'白サシ・紅サシ・赤虫',tip:'繊細〜中間',baseCatch:85,exposure:'dome',special:'基本は底釣り。食い渋り時は小針と小さな誘い。',localItems:['ソースカツ丼','現地釣果情報']},
{id:'hibara_s_ice',lat:37.689,lon:140.071,label:'福島｜桧原湖南部｜氷上',water:'桧原湖南部',style:'氷上',months:[1,2,3],shelf:'底中心',rig:'狐0.8号前後・短め',sinker:'3〜5g',bait:'白サシ・紅サシ・赤虫',tip:'繊細〜中間',baseCatch:110,exposure:'ice',special:'基本は底。終盤は底ベタを丁寧に探る。',localItems:['ソースカツ丼','ホッカイロ']},
{id:'hibara_n_dome',lat:37.735,lon:140.056,label:'福島｜桧原湖北部｜屋形・ドーム',water:'桧原湖北部',style:'屋形・ドーム',months:[11,12,1,2,3],shelf:'底中心',rig:'狐0.8号前後・短ハリス',sinker:'3〜5g',bait:'白サシ・紅サシ',tip:'繊細',baseCatch:75,exposure:'dome',special:'小型傾向。小針と丁寧な誘いが合う。',localItems:['ミルクティー','ソースカツ丼']},
{id:'hibara_n_ice',lat:37.735,lon:140.056,label:'福島｜桧原湖北部｜氷上',water:'桧原湖北部',style:'氷上',months:[1,2,3],shelf:'底中心',rig:'狐0.8号前後・短ハリス',sinker:'3〜5g',bait:'白サシ・紅サシ',tip:'繊細',baseCatch:100,exposure:'ice',special:'小型に寄せると数が伸びやすい。',localItems:['ホッカイロ','チョコパン']},
{id:'onogawa_dome',lat:37.664,lon:140.105,label:'福島｜小野川湖｜ドーム',water:'小野川湖',style:'ドーム',months:[11,12,1,2,3],shelf:'底中心、ときどき中層',rig:'標準 5〜7本針',sinker:'4〜6g',bait:'白サシ・紅サシ',tip:'中間〜やや硬め',baseCatch:90,exposure:'dome',special:'底に良型が混じる。桧原湖よりやや重めが合わせやすい。',localItems:['ホットレモン','厚手手袋']},
{id:'onogawa_ice',lat:37.664,lon:140.105,label:'福島｜小野川湖｜氷上',water:'小野川湖',style:'氷上',months:[1,2,3],shelf:'底中心、ときどき中層',rig:'標準 5〜7本針',sinker:'4〜6g',bait:'白サシ・紅サシ',tip:'中間〜やや硬め',baseCatch:120,exposure:'ice',special:'中層は小型、底は良型のパターンを意識。',localItems:['ホットレモン','厚手手袋']}
];

const names=['愚者','魔術師','女教皇','女帝','皇帝','法王','恋人達','戦車','力','隠者','運命の輪','正義','吊るされたワカサギ','死神','節制','悪魔','塔','星','月','太陽','審判','世界'];
const nums=['0','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI'];
const slugs=['fool','magician','priestess','empress','emperor','hierophant','lovers','chariot','strength','hermit','wheel','justice','hanged','death','temperance','devil','tower','star','moon','sun','judgement','world'];
const ranks=['B','A','A','A','A','A','A','S','A','B','S','A','C','B','A','C','D','A','B','SS','S','SS'];
const effects=[.95,1.12,1.06,1.14,1.15,1.08,1.10,1.28,1.14,1.00,1.24,1.12,.78,1.03,1.08,.74,.55,1.18,.92,1.42,1.22,1.50];
const taglines=['定番を外れた先に群れがいる。','小さな工夫が大きな差になる。','静かな穂先だけが答えを知る。','豊かな魚影と満ちた気配。','王道を守る者に安定が宿る。','現地の助言がそのまま近道になる。','当たり餌との相性が今日を決める。','群れが入ったら迷わず手返し。','小さな存在が大きな流れを制する。','静かな穴にだけ残る一匹がいる。','時合いは巡る。備えた者が取る。','棚が合えば湖は答えを返す。','今日は焦った者から見放される。','古い正解を捨てた先に流れが変わる。','誘いと止めの調和が鍵になる。','反応はあるのに口を使わぬ日。','今日は安全が最大の大漁。','早起きした者にだけ見える吉兆。','魚探の反応が真実とは限らない。','爆釣の光が湖を照らす。','去った群れがもう一度戻ってくる。','すべてが噛み合う完成の一日。'];
const oracle=['思い切って場所や棚を変えると流れが動く。','仕掛けの一部だけ変える。大改造より小変更が効く。','穂先の小さな違和感を拾う。誘い過ぎない。','魚影が濃い日。連掛けを狙って手返しを上げる。','基本通りが強い。迷ったら定番の棚・餌へ戻す。','現地の釣れている人の情報を素直に採用する。','餌交換を惜しまない。今日の答えは鮮度にある。','時合いは短い。入った瞬間に一気に数を伸ばす。','強引に動かさず、落ち着いた操作で群れを留める。','周囲より静かな場所に答えがある。粘る価値あり。','波がある日。釣れる時間に集中して休む時間は休む。','棚合わせが最優先。数十cmのズレを詰める。','動かない勇気。反応が出てもすぐ仕掛けを動かさない。','昨日の正解を捨てる。仕掛け・穴・誘いをリセット。','大きく誘って小さく止める。メリハリを整える。','難しい日。数より一匹ずつ確実に掛ける。','無理をしない。風・氷・足場が悪ければ撤退も正解。','朝一勝負。開始直後の良い時間を逃さない。','魚探に映っても食わない群れを深追いしない。','強い日。手返し・餌交換・魚外しの速度がそのまま釣果になる。','一度抜けた群れが戻る。片付けを急がない。','棚・餌・仕掛けが噛み合う日。今の形を崩さず継続。'];
const cards=names.map((name,i)=>({index:i,n:nums[i],name,rank:ranks[i],effect:effects[i],tagline:taglines[i],oracle:oracle[i],image:`assets/tarot/${String(i).padStart(2,'0')}-${slugs[i]}.webp`}));

const $=id=>document.getElementById(id);
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

function fillLocations(){const sel=$('location');sel.innerHTML='';locations.forEach((l,i)=>{const o=document.createElement('option');o.value=l.id;o.textContent=l.label;if(l.id==='hanayama_dome')o.selected=true;sel.appendChild(o)});}
function chooseCard(mode,seed){let pool=cards;let weights;if(mode==='oni'){pool=cards.filter(c=>['B','C','D'].includes(c.rank));weights=pool.map(c=>c.rank==='D'?8:c.rank==='C'?6:4)}else if(mode==='hard'){weights=pool.map(c=>c.rank==='SS'?2:c.rank==='S'?4:c.rank==='A'?6:c.rank==='B'?6:c.rank==='C'?5:4)}else{weights=pool.map(c=>c.rank==='SS'?2:c.rank==='S'?4:c.rank==='A'?7:c.rank==='B'?4:c.rank==='C'?2:1)}let total=weights.reduce((a,b)=>a+b,0),r=(seed%100000)/100000*total;for(let i=0;i<pool.length;i++){if(r<weights[i])return pool[i];r-=weights[i]}return pool[0];}
function seasonInfo(date,l){const m=date.getMonth()+1;if(!l.months.includes(m))return{factor:.35,label:'期間外',note:'現在はこの釣り場の基本シーズン外。来季への準備運として占います。'};if([10,11].includes(m))return{factor:.85,label:'開幕期',note:'開幕期。群れが安定しないため変化への対応を早めに。'};if([1,2].includes(m))return{factor:1.08,label:'本番期',note:'本番期。条件が噛み合えば数を伸ばせる季節。'};return{factor:.95,label:'終盤期',note:'終盤。食い渋りと底寄りを意識。'};}
function weatherCode(code){if(code===0)return'快晴';if([1,2,3].includes(code))return'晴れ〜曇り';if([45,48].includes(code))return'霧';if(code>=51&&code<=67)return'雨・みぞれ';if(code>=71&&code<=77)return'雪';if(code>=80&&code<=82)return'にわか雨';if(code>=85&&code<=86)return'雪';return'変わりやすい天気';}
async function getWeather(l,date){const today=new Date();today.setHours(0,0,0,0);const d=new Date(date);d.setHours(0,0,0,0);const diff=Math.round((d-today)/86400000);if(diff<0||diff>15)return{available:false,condition:'予報圏外',temp:null,wind:null,factor:1,note:'天気はまだ予報圏外。神託は季節と釣り場データ中心。'};try{const ds=date.toISOString().slice(0,10);const url=`https://api.open-meteo.com/v1/forecast?latitude=${l.lat}&longitude=${l.lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,wind_speed_10m_max&timezone=Asia%2FTokyo&start_date=${ds}&end_date=${ds}`;const r=await fetch(url);if(!r.ok)throw new Error('weather');const j=await r.json();const max=j.daily.temperature_2m_max?.[0],min=j.daily.temperature_2m_min?.[0],wind=j.daily.wind_speed_10m_max?.[0],code=j.daily.weather_code?.[0];const mean=(max+min)/2;let factor=1;if(wind>25)factor*=.78;else if(wind>15)factor*=.9;if(mean<-8)factor*=.9;return{available:true,condition:weatherCode(code),temp:`${min.toFixed(0)}〜${max.toFixed(0)}℃`,wind:`最大 ${wind.toFixed(0)}km/h`,windValue:wind,factor,note:wind>25?'強風注意。安全と仕掛けの安定を優先。':wind>15?'風あり。オモリは上限寄りが無難。':'風は比較的穏やか。軽めも選択肢。'};}catch(e){return{available:false,condition:'取得できず',temp:'--',wind:'--',factor:1,note:'天気情報を取得できなかったため、釣り場データ中心で表示。'};}}
function narrowSinker(l,w){if(!w.available)return l.sinker;const v=w.windValue||0;if(l.id==='minamikawa_bridge')return v>25?'14〜18g':v>15?'10〜14g':'7〜10g';if(l.id==='hanayama_dome')return v>22?'赤 7〜10g':'赤 5〜7g';const m=l.sinker.match(/(\d+)\D+(\d+)g/);if(!m)return l.sinker;let a=+m[1],b=+m[2];return v>22?`${Math.max(a+1,b-1)}〜${b+2}g`:v>14?`${Math.max(a,b-1)}〜${b}g`:`${a}〜${Math.max(a,b-1)}g`;}
function rankMetal(r){return r==='SS'?'PLATINUM':r==='S'?'GOLD':r==='A'?'SILVER':r==='B'?'BRONZE':r==='C'?'WHITE': 'BLACK';}
function buildCatch(l,c,s,w,mode,seed){let f=l.baseCatch*c.effect*s.factor*w.factor;f*=mode==='hard'?.82:mode==='oni'?.62:1;const jitter=.82+((seed%37)/100);const center=Math.max(3,Math.round(f*jitter));const low=Math.max(1,Math.round(center*.7)),high=Math.max(low+1,Math.round(center*1.3));let stars=clamp(Math.round(2.5+c.effect*1.5+(s.factor-1)*2+(w.factor-1)*2),1,5);return{center,low,high,stars};}
function adjustGuidance(l,c,w,seed){let shelf=l.shelf,rig=l.rig,bait=l.bait,tip=l.tip,sinker=narrowSinker(l,w);if(c.index===11)shelf+='｜今日は棚合わせ最優先';if(c.index===2||c.index===9)tip+='｜小さなアタリ重視';if(c.index===6)bait+='｜交換頻度高め';if(c.index===7)rig+='｜手返し優先';if(c.index===12)rig+='｜誘いを減らす';if(c.index===13)rig+='｜途中で変更も吉';if(c.index===16)sinker+='｜無理なら撤退';return{shelf,rig,bait,tip,sinker};}
function localItem(l,seed){return l.localItems[seed%l.localItems.length];}
function renderGallery(){const grid=$('galleryGrid');grid.innerHTML='';let loaded=0,failed=0;cards.forEach(c=>{const item=document.createElement('article');item.className='gallery-card';const img=document.createElement('img');img.src=c.image;img.alt=`${c.n} ${c.name}`;img.loading='lazy';img.onload=()=>{loaded++;updateStatus()};img.onerror=()=>{failed++;item.classList.add('image-error');img.alt=`${c.name}（画像読込エラー）`;updateStatus()};const p=document.createElement('p');p.innerHTML=`<span>${c.n}</span><b>${c.name}</b>`;item.append(img,p);grid.appendChild(item)});function updateStatus(){if(loaded+failed===22)$('galleryStatus').textContent=failed?`画像確認：${loaded}/22 正常・${failed}枚エラー`:'画像確認：22/22 正常';}}
async function runFortune(e){e?.preventDefault();const l=locations.find(x=>x.id===$('location').value)||locations[0];const ds=$('tripDate').value;if(!ds)return;const date=new Date(`${ds}T12:00:00+09:00`);const mode=$('mode').value;const seed=hash(`${ds}|${l.id}|${mode}|wakasagi-v2`);const card=chooseCard(mode,seed);const season=seasonInfo(date,l);$('emptyState').classList.add('hidden');$('resultContent').classList.remove('hidden');$('resultLocation').textContent=l.label;$('resultMeta').textContent=`${ds}｜${mode==='oni'?'鬼HARD':mode.toUpperCase()}｜${season.label}`;$('seasonAlert').textContent=season.note;$('tarotImage').src=card.image;$('tarotImage').alt=`${card.n} ${card.name}`;$('tarotImage').onerror=()=>{$('tarotImage').alt=`${card.name}：画像読み込みエラー`;$('tarotCard').classList.add('image-error')};$('tarotRankBadge').textContent=`${card.rank} RANK`;$('rankDisc').textContent=card.rank;$('rankMetal').textContent=rankMetal(card.rank);$('tarotNumber').textContent=card.n;$('tarotName').textContent=card.name;$('oracleText').textContent=card.oracle;$('tarotTagline').textContent=card.tagline;$('weatherCondition').textContent='天気取得中';$('weatherTemp').textContent='--';$('weatherWind').textContent='--';const w=await getWeather(l,date);$('weatherCondition').textContent=w.condition;$('weatherTemp').textContent=w.temp??'予報圏外';$('weatherWind').textContent=w.wind??'予報圏外';const g=adjustGuidance(l,card,w,seed);$('guideShelf').textContent=g.shelf;$('guideRig').textContent=g.rig;$('guideSinker').textContent=g.sinker;$('guideBait').textContent=g.bait;$('guideTip').textContent=g.tip;const c=buildCatch(l,card,season,w,mode,seed);$('catchMain').textContent=`約 ${c.center} 匹`;$('catchRange').textContent=`目安 ${c.low}〜${c.high}匹`;$('stars').textContent='★'.repeat(c.stars)+'☆'.repeat(5-c.stars);$('catchText').textContent=`${w.note} ${card.tagline}`;$('luckyItem').textContent=localItem(l,seed);$('localTip').textContent=l.special;setTimeout(()=>document.querySelector('.result-panel').scrollIntoView({behavior:'smooth',block:'start'}),80);}

$('fortune-form').addEventListener('submit',runFortune);$('againBtn').addEventListener('click',()=>$('fortune-form').requestSubmit());$('galleryBtn').addEventListener('click',()=>{$('gallery').classList.remove('hidden');$('gallery').scrollIntoView({behavior:'smooth'});});$('closeGallery').addEventListener('click',()=>{$('gallery').classList.add('hidden');document.querySelector('.form-panel').scrollIntoView({behavior:'smooth'});});
fillLocations();$('tripDate').value=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});renderGallery();
