const VERSION='clean2-20260809';
const CARD_BASE='./assets/tarot/';
const cards=[
['0','愚者','00-fool.webp','定番を外れた先に群れがいる。'],['I','魔術師','01-magician.webp','小さな工夫が大きな差になる。'],['II','女教皇','02-priestess.webp','静かな穂先だけが答えを知る。'],['III','女帝','03-empress.webp','豊かな魚影と満ちた気配。'],['IV','皇帝','04-emperor.webp','王道を守る者に安定が宿る。'],['V','法王','05-hierophant.webp','現地の助言がそのまま近道になる。'],['VI','恋人達','06-lovers.webp','当たり餌との相性が今日を決める。'],['VII','戦車','07-chariot.webp','群れが入ったら迷わず手返し。'],['VIII','力','08-strength.webp','小さな存在が大きな流れを制する。'],['IX','隠者','09-hermit.webp','静かな穴にだけ残る一匹がいる。'],['X','運命の輪','10-wheel.webp','時合いは巡る。備えた者が取る。'],['XI','正義','11-justice.webp','棚が合えば湖は答えを返す。'],['XII','吊るされたワカサギ','12-hanged.webp','今日は焦った者から見放される。'],['XIII','死神','13-death.webp','古い正解を捨てた先に流れが変わる。'],['XIV','節制','14-temperance.webp','誘いと止めの調和が鍵になる。'],['XV','悪魔','15-devil.webp','反応はあるのに口を使わぬ日。'],['XVI','塔','16-tower.webp','今日は安全が最大の大漁。'],['XVII','星','17-star.webp','早起きした者にだけ見える吉兆。'],['XVIII','月','18-moon.webp','魚探の反応が真実とは限らない。'],['XIX','太陽','19-sun.webp','爆釣の光が湖を照らす。'],['XX','審判','20-judgement.webp','去った群れがもう一度戻ってくる。'],['XXI','世界','21-world.webp','すべてが噛み合う完成の一日。']
].map((x,i)=>({id:i,num:x[0],name:x[1],file:x[2],tagline:x[3],url:`${CARD_BASE}${x[2]}?v=${VERSION}`}));

const locations=[
{id:'anenuma_ice',label:'青森｜姉沼｜氷上',lat:40.749,lon:141.322,months:[1,2],shelf:'浅場中心',rig:'短め4〜6本針',sinker:'2〜4g',bait:'白サシ・紅サシ',tip:'繊細〜中間',base:120,note:'汽水湖で氷が緩みやすい。安全確認を最優先。'},
{id:'gandoko_ice',label:'岩手｜岩洞湖｜氷上',lat:39.804,lon:141.149,months:[1,2,3],shelf:'魚探で浅場・深場を選択',rig:'5〜7本針',sinker:'3〜5g',bait:'白サシ・紅サシ',tip:'先調子〜中間',base:140,note:'同一ポイント2日目は落ちることがある。移動判断を早めに。'},
{id:'gandoko_dome',label:'岩手｜岩洞湖｜ドーム船',lat:39.804,lon:141.149,months:[11,12,1,2,3],shelf:'底中心',rig:'5〜7本針',sinker:'4〜5g',bait:'白サシ・紅サシ',tip:'柔らかめ〜中間',base:45,note:'小さな変化を拾う釣りが吉。'},
{id:'sai_ice',label:'岩手｜菜魚湖・大志田ダム｜氷上',lat:39.741,lon:141.378,months:[1,2],shelf:'底中心',rig:'5本前後',sinker:'3〜5g',bait:'サシ系',tip:'中間',base:90,note:'開催状況など現地情報を最優先。'},
{id:'hanayama_dome',label:'宮城｜花山湖｜ドーム船',lat:38.789,lon:140.857,months:[11,12,1,2,3],shelf:'底〜中層',rig:'底5本／中層7本',sinker:'赤5〜7g',bait:'赤虫・紅サシ',tip:'連掛け向き・やや硬め',base:180,note:'蛍光より赤オモリ。小型が多く手返し重視。'},
{id:'minamikawa_bridge',label:'宮城｜南川ダム｜橋上',lat:38.411,lon:140.905,months:[10,11,12,1,2],shelf:'底中心',rig:'長め4〜8本針',sinker:'7・10・14g中心',bait:'サシ・赤虫',tip:'硬め＋延長30cm',base:95,note:'朝、特に8時前が強い。風が出たら重めへ。'},
{id:'wakuya_pier',label:'宮城｜涌谷町釣り公園｜桟橋',lat:38.543,lon:141.134,months:[10,11,12,1,2],shelf:'魚探シューティング',rig:'5本針・1.5号以上',sinker:'3〜5g',bait:'白サシ',tip:'大型対応・硬め',base:18,note:'大型狙い。猫が後ろに付いたら吉兆。'},
{id:'towada_dome',label:'秋田｜十和田湖・小坂側｜ドーム船',lat:40.442,lon:140.887,months:[11,12,1,2,3],shelf:'深場中心',rig:'5〜7本針',sinker:'4〜6g',bait:'サシ系',tip:'中間',base:60,note:'風による運休など最新営業情報を確認。'},
{id:'hibara_s_dome',label:'福島｜桧原湖南部｜屋形・ドーム',lat:37.689,lon:140.071,months:[11,12,1,2,3],shelf:'底中心',rig:'狐0.8号前後・短め',sinker:'3〜5g',bait:'白サシ・紅サシ・赤虫',tip:'繊細〜中間',base:85,note:'食い渋りは小針と小さな誘い。'},
{id:'hibara_s_ice',label:'福島｜桧原湖南部｜氷上',lat:37.689,lon:140.071,months:[1,2,3],shelf:'底中心',rig:'狐0.8号前後・短め',sinker:'3〜5g',bait:'白サシ・紅サシ・赤虫',tip:'繊細〜中間',base:110,note:'終盤は底ベタを丁寧に。'},
{id:'hibara_n_dome',label:'福島｜桧原湖北部｜屋形・ドーム',lat:37.735,lon:140.056,months:[11,12,1,2,3],shelf:'底中心',rig:'狐0.8号前後・短ハリス',sinker:'3〜5g',bait:'白サシ・紅サシ',tip:'繊細',base:75,note:'小型傾向。小針と丁寧な誘い。'},
{id:'hibara_n_ice',label:'福島｜桧原湖北部｜氷上',lat:37.735,lon:140.056,months:[1,2,3],shelf:'底中心',rig:'狐0.8号前後・短ハリス',sinker:'3〜5g',bait:'白サシ・紅サシ',tip:'繊細',base:100,note:'小型に寄せると数が伸びやすい。'},
{id:'onogawa_dome',label:'福島｜小野川湖｜ドーム',lat:37.664,lon:140.105,months:[11,12,1,2,3],shelf:'底中心、ときどき中層',rig:'5〜7本針',sinker:'4〜6g',bait:'白サシ・紅サシ',tip:'中間〜やや硬め',base:90,note:'底に良型が混じる。'},
{id:'onogawa_ice',label:'福島｜小野川湖｜氷上',lat:37.664,lon:140.105,months:[1,2,3],shelf:'底中心、ときどき中層',rig:'5〜7本針',sinker:'4〜6g',bait:'白サシ・紅サシ',tip:'中間〜やや硬め',base:120,note:'中層は小型、底は良型を意識。'}
];

const oracle=['思い切って場所や棚を変えると流れが動く。','仕掛けの一部だけ変える。大改造より小変更が効く。','穂先の小さな違和感を拾う。誘い過ぎない。','魚影が濃い日。連掛けを狙って手返しを上げる。','基本通りが強い。迷ったら定番へ戻す。','現地の釣れている人の情報を素直に採用。','餌交換を惜しまない。鮮度が答え。','時合いは短い。入った瞬間に一気に数を伸ばす。','強引に動かさず、落ち着いた操作で群れを留める。','周囲より静かな場所に答えがある。','波がある日。釣れる時間に集中。','棚合わせ最優先。数十cmのズレを詰める。','動かない勇気。反応が出ても焦らない。','昨日の正解を捨ててリセット。','大きく誘って小さく止める。','難しい日。一匹ずつ確実に。','無理をしない。安全が最優先。','朝一勝負。開始直後を逃さない。','魚探反応だけで決めつけない。','好条件。手返しと餌交換を上げる。','去った群れが戻る。見切りを急がない。','すべてが噛み合う日。基本を崩さない。'];
const effects=[.95,1.12,1.06,1.14,1.15,1.08,1.10,1.28,1.14,1.00,1.24,1.12,.78,1.03,1.08,.74,.55,1.18,.92,1.42,1.22,1.50];
const $=id=>document.getElementById(id);
function hash(s){let h=2166136261;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function chooseCard(seed,mode){const h=hash(seed);if(mode==='oni'){const pool=[12,15,16,18,13,9,0];return cards[pool[h%pool.length]]}if(mode==='hard'){const pool=[0,9,12,13,15,16,18,11,14];return cards[pool[h%pool.length]]}return cards[h%cards.length]}
function seasonFactor(date,loc){const m=date.getMonth()+1;return loc.months.includes(m)?1:.35}
function calcCatch(loc,card,date,mode){let v=loc.base*effects[card.id]*seasonFactor(date,loc);if(mode==='hard')v*=.82;if(mode==='oni')v*=.62;const wobble=.86+(hash(loc.id+date.toISOString().slice(0,10))%29)/100;v*=wobble;const low=Math.max(0,Math.round(v*.72));const high=Math.max(low+1,Math.round(v*1.28));return `${low}〜${high}匹`}
async function weather(loc,date){const today=new Date();const delta=Math.round((date-today)/(86400000));if(delta<-1||delta>15)return null;const d=date.toISOString().slice(0,10);const u=`https://api.open-meteo.com/v1/forecast?latitude=${loc.lat}&longitude=${loc.lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,wind_speed_10m_max&timezone=Asia%2FTokyo&start_date=${d}&end_date=${d}`;try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)return null;const j=await r.json();return{min:j.daily.temperature_2m_min?.[0],max:j.daily.temperature_2m_max?.[0],wind:j.daily.wind_speed_10m_max?.[0]}}catch{return null}}
function setCardImage(img,card){img.alt=`${card.num} ${card.name}`;img.src=card.url;img.onerror=()=>{img.removeAttribute('src');img.alt=`画像読込失敗: ${card.file}`}}
function populateLocations(){const s=$('location');s.innerHTML='';for(const l of locations){const o=document.createElement('option');o.value=l.id;o.textContent=l.label;s.appendChild(o)}s.value='hanayama_dome'}
async function validateCards(){const grid=$('galleryGrid');grid.innerHTML='';let ok=0;const jobs=cards.map(card=>new Promise(resolve=>{const wrap=document.createElement('article');wrap.className='gallery-card';const box=document.createElement('div');box.className='imagebox';const img=new Image();img.alt=`${card.num} ${card.name}`;const foot=document.createElement('footer');foot.innerHTML=`<span>${card.num}</span><strong>${card.name}</strong>`;img.onload=()=>{wrap.classList.add('good');ok++;box.appendChild(img);resolve()};img.onerror=()=>{wrap.classList.add('bad');const m=document.createElement('div');m.className='missing';m.textContent='?';box.appendChild(m);resolve()};img.src=card.url;wrap.append(box,foot);grid.appendChild(wrap)}));await Promise.all(jobs);$('galleryStatus').textContent=`画像確認: ${ok}/22 正常${ok===22?' ✓':' — 読めない画像があります'}`;return ok}
async function runFortune(){const loc=locations.find(x=>x.id===$('location').value)||locations[0];const date=new Date($('tripDate').value+'T12:00:00');const mode=$('mode').value;const card=chooseCard(`${loc.id}|${$('tripDate').value}|${mode}`,mode);$('emptyState').classList.add('hidden');$('result').classList.remove('hidden');$('resultLocation').textContent=loc.label;$('resultMeta').textContent=loc.months.includes(date.getMonth()+1)?'シーズン内':'期間外：来季への神託';$('tarotNumber').textContent=card.num;$('tarotName').textContent=card.name;$('oracleText').textContent=oracle[card.id];$('tagline').textContent=card.tagline;$('shelf').textContent=loc.shelf;$('rig').textContent=loc.rig;$('sinker').textContent=loc.sinker;$('bait').textContent=loc.bait;$('tip').textContent=loc.tip;$('catchRange').textContent=calcCatch(loc,card,date,mode);$('localTip').textContent=loc.note;setCardImage($('tarotImage'),card);$('weatherText').textContent='天気確認中';$('weatherNumbers').textContent='--';const w=await weather(loc,date);if(w){$('weatherText').textContent='予報';$('weatherNumbers').textContent=`${w.min}〜${w.max}℃ / 風 ${w.wind}km/h`}else{$('weatherText').textContent='予報圏外';$('weatherNumbers').textContent='実釣データ中心'}}

document.addEventListener('DOMContentLoaded',async()=>{populateLocations();const now=new Date();$('tripDate').value=now.toISOString().slice(0,10);$('fortuneForm').addEventListener('submit',e=>{e.preventDefault();runFortune()});$('againBtn').addEventListener('click',runFortune);$('galleryBtn').addEventListener('click',async()=>{$('gallery').classList.remove('hidden');await validateCards();$('gallery').scrollIntoView({behavior:'smooth',block:'start'})});$('closeGallery').addEventListener('click',()=>$('gallery').classList.add('hidden'));await validateCards();console.info('Wakasagi clean rebuild',VERSION)})